config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root :to => 'posts#index'

  resources :posts do
    resources :tags, except: [:index]
  end

  resources :tags, except: [:index] do 
    resources :posts
  end
end

app/models/post.rb
class Post<ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :tags
  has_attached_file :image, default_url: "/images/:style/missing.png"

  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  validates_presence_of :image, :caption
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :posts

  validates_presence_of :name
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController<ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:notice] = "Post created."
      redirect_to posts_path
    else
      flash[:alert] = "There was an error."
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private
  def post_params
    params.require(:post).permit(:title, :image, :caption)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    @post = Post.find(params[:post_id])
    @tag = Tag.find(params[:id])
  end

  def new
    @post = Post.find(params[:post_id])
    @tag = @post.tags.new
  end

  def create
    @post = Post.find(params[:post_id])
    @tag = @post.tags.new(tag_params)
    if @tag.save
      flash[:notice] = "Tag created."
      redirect_to post_path(@tag.post)
    else
      flash[:alert] = "There was an error."
      render :new
    end
  end

  # def edit
  #
  # end
  #
  # def update
  #
  # end
  #
  # def destroy
  #
  # end

  private
  def tag_params
    params.require(:tag).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flickr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="/">Flickr</a>
      </div>
      <div>
        <ul class="nav navbar-nav">
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><%= link_to "", new_post_path, class: "glyphicon glyphicon-cloud-upload" %></li>
            <li><%= link_to 'You', edit_user_registration_path %></li>
            <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to 'Sign In', new_user_session_path %></li>
            <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>

  <%= flash[:alert] %>
  <%= flash[:notice] %>

<div class='container'>
  <%= yield %>  
</div>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>

<div class="form-group">
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>
  <%= f.label :image %>
  <%= f.file_field :image %>
  <br>
  <%= f.label :caption %>
  <%= f.text_field :caption %>
  <br>
  <%= f.submit %>
</div>

<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<h1>First Post Test</h1>

  <% @posts.each do |post| %>
    <h3><%= post.title %></h3>
    <p><%= link_to image_tag(post.image), post_path(post) %></p>
  <% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<% if user_signed_in? %>
  <%= render 'form' %>
<% else %>
  <p>You must be signed in to make a new post.</p>
<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<p><%= image_tag(@post.image, :alt => "Goldendoodle puppy") %></p>

<p><%= @post.caption %></p>

<h3>Tags:</h3>

<ul>
  <% @post.tags.each do |tag| %>
    <li><%= link_to tag.name, post_tag_path(@post, tag) %> |
        <%= link_to "Edit", edit_post_tag_path(@post, tag) %>
        <%= link_to "Delete", post_path(@post), method: :delete %>
    </li>
  <% end %>
</ul>

<%= link_to "Edit Post", edit_post_path(@post) %>
<%= link_to "Delete Post", post_path(@post), method: :delete %>

app/views/tags/show.html.erb
<h1><%= @tag.name %></h1>

<ul>
  <% @tag.posts.each do |post| %>
    <li><%= link_to post.title, post_path(post) %></li>
  <% end %>
</ul>

<%= link_to "Edit Tag", edit_post_tag_path(@post, @tag) %>
<%= link_to "Delete Tag", post_path(@post), method: :delete %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>